#ifndef RAND_H
#define RAND_H

#include "config.h"
#include "stdlib.h"

/**
 * @brief Generates a random byte using DRBG (Deterministic Random Bit Generator).
 * 
 * @return A random byte generated by DRBG.
 * @note This function is currently incomplete.
 */
byte DRBG();

/**
 * @brief Returns a random byte.
 * 
 * @details Depending on the `USE_DRBG` option, this function either uses `rand()` from `stdlib` or 
 * the `DRBG()` function to generate a random byte.
 * 
 * @return A random byte.
 */
byte byte_rand();

#endif  // RAND_H