#include "rand.h"

/**
 * @brief Generates a random byte using DRBG (Deterministic Random Bit Generator).
 * 
 * @return A random byte generated by DRBG.
 * @note This function is currently incomplete.
 */
byte DRBG() {
    return rand() % 0xff;   // 미완
}

/**
 * @brief Returns a random byte.
 * 
 * @details Depending on the `USE_DRBG` option, this function either uses `rand()` from `stdlib` or 
 * the `DRBG()` function to generate a random byte.
 * 
 * @return A random byte.
 */
byte byte_rand() {
// USE_DRBG 값에 따른 함수 선정
#if   USE_DRBG == 0
    return rand() % 0xff;   // stdlib 내장 rand() 사용
#elif USE_DRBG == 1
    return DRBG();
#else
    fprintf(stderr, UnSupportUseDRBGValErrMsg);
    return DRBG();
#endif
}