#ifndef RAND_H
#define RAND_H

#include "config.h"
#include "stdlib.h"

/**
 * @brief Generates a random byte using DRBG.
 *
 * @return Returns a random byte generated by DRBG.
 * @note This feature is not yet fully implemented.
 */
byte DRBG(void);

/**
 * @brief Returns a random byte.
 *
 * @details Depending on the 'USE_DRBG' option, this function either uses the 'rand()' or the 'DRBG()' function.
 *
 * @return A randomly generated byte.
 */
byte byte_rand(void);

#endif  // RAND_H
